### ISSUE TITLE
Shoud we make the PR Update outdated Website here?

### ISSUE THREAD

**Issue by soumyadip007** [PointCloudLibrary/documentation#2]
**Update outdated Website**
Create a static website on Github pages or similar
Provide a basic replacement including:
documentation for past releases
prevent invalidation of links as much as possible, while updating the content
Make it the new home for pointclouds.org with HTTPS support
Integrate versioned (documentation+tutorials) to make it the go-to resource for PCL
(Stretch goal) Migrate all content from existing website, including
ability to create blog posts (using Jekyll or similar)
lost content (from internet archives)
Walk through documentation
[Summer of Docs focus] Includes Tutorials, Guides and Examples

Update to reflect forward movement in PCL
Detect and increase coverage

**Comment by SergioRAgostinho** [comment]
The current website is being hosted [here](https://github.com/PointCloudLibrary/PointCloudLibrary.github.io). Some of the things you mentioned were already addressed, others are a "work in progress". Nevertheless, discussion about website related topics, should be done on its own repo.
