### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jruebsam** [PointCloudLibrary/documentation#3]
I just recognized that 

http://pointclouds.org/

is down, is there any reason for this ? 

Best Regards

**Comment by rbrusu** [comment]
yes, i had to shut down the servers, they were extremely old, running very old versions of Ubuntu and got hacked all the time (and due to other real life constraints, I was unable to maintain them). The infrastructure was running modx, which got performance/security issues constantly, and the website was very out of date. 

I'd like to work with @jspricke and @SergioRAgostinho and @taketwo and @kunaltyagi to see which parts of the website were still useful and bring them back separately one by one. We should also aim to take advantage of GitHub services as much as possible in this process.

**Comment by SergioRAgostinho** [comment]
Some breathing room for people looking for api reference
https://pointcloudlibrary.github.io/documentation/

**Comment by jruebsam** [comment]
Thank you very much!
Actually  I tried to build the documentation by myself but the usual 

mkdir build && cmake .. && make 

didn't create any documentation :(

**Comment by kunaltyagi** [comment]
We use [this configuration on our CI](https://github.com/PointCloudLibrary/pcl/blob/master/.ci/azure-pipelines/documentation.yaml):
```
cmake .. -DDOXYGEN_USE_SHORT_NAMES=OFF \
            -DSPHINX_HTML_FILE_SUFFIX=php \
            -DWITH_DOCS=ON \
            -DWITH_TUTORIALS=ON
```

**Comment by kunaltyagi** [comment]
@jspricke Can we have a [pointcloudlibrary.github.io](https://github.com/PointCloudLibrary/pointcloudlibrary.github.io) repository?

**Comment by rbrusu** [comment]
i just redirected the main URL to point to the docs site that @SergioRAgostinho posted

**Comment by lesterlo** [comment]
There has some old but useful tutorial pages on old "pointcloud.org". I hope we can host the website again on the " pointcloudlibrary.github.io" page.

some useful page: "Create cmake file with PCL", "Using PCL on your QT Program"

**Comment by SergioRAgostinho** [comment]
I put the normal tutorials up on read the docs for the time being
https://pcl-tutorials.readthedocs.io/en/latest/

**Comment by jspricke** [comment]
@kunaltyagi I created the repo, ping me if you need help and thanks for working on this!

**Comment by jruebsam** [comment]
Thank you for the fast solution ! Best regards

**Comment by SergioRAgostinho** [comment]
@jspricke can we make it public so that users can submit normal PRs if desired?

**Comment by jspricke** [comment]
Done, I thought I created it public and without the test at the end, did someone change that?

**Comment by kunaltyagi** [comment]
The new repo caused havoc in github page's redirection, so I tried to reset the effect, by making it private, but it didn't work. It worked after I renamed it, but then I forgot to make it public again.

**Comment by jspricke** [comment]
website is back online, thanks to all of you!
